### ISSUE TITLE
请求大佬进行修复，新版内核的浏览器传参异常，猫抓不能调用N_m3u8DL-RE

### ISSUE THREAD

**Issue by siizz** [xifangczy/URLProtocol#3]
更新了一波浏览器（brave跟vivaldi）内核版本升级到了Chromium  130.0.6723.70之后，URLProtocol获取出来的URL在http://或https://会丢失:
![2024-10-29_120756](https://github.com/user-attachments/assets/fe5ba725-21e7-4132-84aa-84dfdad68c02)

**Comment by xifangczy** [comment]
和该项目无关。

这是Chromium 130做了调整 具体查看 https://github.com/xifangczy/cat-catch/issues/528

猫抓扩展已经进行了更新。请更新猫抓版本。
