### ISSUE TITLE
Custom url modification in chromium browsers

### ISSUE THREAD

**Issue by trimechee** [xifangczy/URLProtocol#4]
Hi, maybe it will be more appropriate  to repost my issue here, because Mr Xifangczy informed me that there are modifications to the custom url protocol in chrome and preview with potplayer is not related to Cat-Catch project and so , may be the new custon url protocol of chromium browsers is related to urlprotocol and we hope this it will be fixed please because press articles, technical reviewers, users...
say potplayer is one or the best media player in the worlds, it has good video quality enhancements, deinterlacing, filters, light power, youtube.....and support custom potplayer protocol via urlprotocol is very important :

 https://github.com/xifangczy/cat-catch/issues/536

**Comment by xifangczy** [comment]
Unrelated to the project

**Comment by trimechee** [comment]
Mr @andy-portmen, you are the last hope of humanity to be able to preview with poptlayer, we hope please the magnificent exceptional extension Open-in-vlc will add support for potplayer since Urlprotocol and Cat-Catch seems to no longer support preview with potplayer anymore .....

**Comment by xifangczy** [comment]
You should look for potplayer to solve it, not cat-catch and URLProtocol.

**Comment by trimechee** [comment]
Potplayer doesn't have forum, mail, discord, twitter, facebook...i can't contact them, and also i am not developer and i can't discuss them avout custom url probelmatics....., and the hope is the rare Open-in-vlc extension will support potplayer because i tried and it doesnt work ......          
  vlc 4 stable seems it will not be released soon.....in vlc i can't stetch video in my little eee pc... the strange but good  thing preview with potplayer with cat catch works in firefox, so the probem seems to be in chromium browsers....

**Comment by trimechee** [comment]
i remember when i have problem to download some videos with the great Media-Downloader, the problem was related in yt-dlp and not directly to M-D,  but the developer of M-D Mr @mhogomchungu himself open issue in yt-dlp page and discuss with the developers the solutions to fix the problem and it was fixed....

**Comment by trimechee** [comment]
Hi Mr @xifangczy , i make new test beause catsxp make new version, preview with potplyaer doesn't work with Cat Catch but i discover interesting thing : when i manually copy past the m3u8 link detected by Cat Catch in potplyer, the playback works in potplayer !!! maybe add my vital tip in FAQ of Cat Catch to inform the users , thanks !
 
https://livetv.sx/frx/showvideo/1380288_liverpool_real_madrid/


preview with potplayer and  Cat catch works without problem in firefox 


i also contact and send mail to potplayer support team to explain them the situation and to fix chromium custom url problem

**Comment by trimechee** [comment]
aieee my tip copy paste manually doesn't work with alls sites, my trick doens't work with vidmoly videos.....i don't know what happes with chromium, this is sad , i can't no more watch videos while downloading, i can't preview video with potplayer.....it seems google want users to stay in the browser , i am ko destroyed, the only solution, migrate to firefox, there i can at least preview with potpayer and we hope Cat catch will continue to support preview with potpayer vital lfe saver featre in freedom firefox browser please

**Comment by trimechee** [comment]
UPDATE :

after the recent disaster catastrophe, because I can no longer watch the video while it is downloading nor preview with potplayer in catsxp browser, I migrate to r3dfox but the central problem remains, I can no longer watch the video while it is downloading, and there I have an idea: I migrate to supermium browser and there, I can finally preview with potplayer and watch the video while it is downloading !!! surely because supermium browser uses chromium kernel 126 LTS, the same for Thorium Legacy browser! really it makes our life difficult all these modifications of chromium ....... Mr @xifangczy , can you please add an option in Cat-Catch where we can see the temporary file being downloaded in the recent chromium kernel 131 ? I think i will open new issue because it is a vital life saver problem for me who has a weak connection

**Comment by trimechee** [comment]
Update : aieee, i download hls video,  even in Supermium browser which use chromium 126 LTS kernel, i can't see temporary hls video in download folder and i can't playback the temporary video while downloading, this is disaster....we hope Cat-Catch will put temporary hls video in specefic folder when we can see and playback the temporary video please, thanks !

**Comment by trimechee** [comment]
UPDATE ! 

I'm gonna cry with joy! The problem is fixed! Potplayer replied to my  mail!! :

"That is already solved in deverloper version~~

https://t1.daumcdn.net/potplayer/beta/PotPlayerSetup64.exe

sorry Mr @xifangczy to have disrupt you wth my so many requests and questions :(
